<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

define( 'WOOMULTI_CURRENCY_F_DIR', WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . 'woo-multi-currency' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_ADMIN', WOOMULTI_CURRENCY_F_DIR . 'admin' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_TEMPLATES', WOOMULTI_CURRENCY_F_DIR . 'templates' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_FRONTEND', WOOMULTI_CURRENCY_F_DIR . 'frontend' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_LANGUAGES', WOOMULTI_CURRENCY_F_DIR . 'languages' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_INCLUDES', WOOMULTI_CURRENCY_F_DIR . 'includes' . DIRECTORY_SEPARATOR );

define( 'WOOMULTI_CURRENCY_F_CSS', WP_PLUGIN_URL . '/woo-multi-currency/css/' );
define( 'WOOMULTI_CURRENCY_F_CSS_DIR', WOOMULTI_CURRENCY_F_DIR . 'css' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_JS', WP_PLUGIN_URL . '/woo-multi-currency/js/' );
define( 'WOOMULTI_CURRENCY_F_JS_DIR', WOOMULTI_CURRENCY_F_DIR . 'js' . DIRECTORY_SEPARATOR );
define( 'WOOMULTI_CURRENCY_F_IMAGES', WP_PLUGIN_URL . '/woo-multi-currency/images/' );
define( 'WOOMULTI_CURRENCY_F_FLAG', WOOMULTI_CURRENCY_F_IMAGES . 'flag/' );

if ( is_file( WOOMULTI_CURRENCY_F_INCLUDES . 'data.php' ) ) {
    require_once WOOMULTI_CURRENCY_F_INCLUDES . 'data.php';
}

if ( is_file( WOOMULTI_CURRENCY_F_INCLUDES . 'functions.php' ) ) {
    require_once WOOMULTI_CURRENCY_F_INCLUDES . 'functions.php';
}

vi_include_folder( WOOMULTI_CURRENCY_F_ADMIN, 'WOOMULTI_CURRENCY_F_Admin_' );
vi_include_folder( WOOMULTI_CURRENCY_F_FRONTEND, 'WOOMULTI_CURRENCY_F_Frontend_' );
